### PR TITLE
Only append element to xml output if value is not empty

### PR DESCRIPTION
**Pull request by twiro**
Fixes https://github.com/symphonists/reflectionfield/issues/32

### CODE REVIEW

**Comment by nitriques** [comment]
I see the value getting removed from the XML, but not the param pool (as mentioned in #37). Is this intentional ?

**Comment by twiro** [comment]
_> Is this intentional ?_

Nope ;) I will update the PR asap! Just give me a few minutes…

**Comment by nitriques** [comment]
Np, thanks @twiro

**Comment by twiro** [comment]
> _I see the value getting removed from the XML, but not the param pool (as mentioned in #37). Is this intentional ?_

Hm… I thought i'd be able to quickly fix this using [getParameterPoolValue](http://www.getsymphony.com/learn/api/2.7.0/toolkit/field/#getParameterPoolValue) but obviously that's not possible – the only method I currently see to avoid empty parameters in the parameter pool is by blocking reflection field from saving fields without values to the database.

Currently reflection field stores a set of "NULL"-values if the reflection doesn't return a valid string – and that's what causing the empty parameters I guess…

I assume storing these null-values could be avoided, but I'm not sure if this might cause other problems (like with the already troublesome frontend-editing) – what do you think?

**Comment by nitriques** [comment]
Yeah you are right.

If the SQL uses LEFT JOIN, not inserting a null value would yield the same results. If it's INNER JOIN, it would not.

From a quick search, I see that all joins are LEFT JOIN, so I would assume it is safe to do.

**Comment by nitriques** [comment]
Do you want me to merge this in and wait for another PR or do you want to add more commits to it ?

**Pull request merged**
